# Generated by Django 2.2.12 on 2020-09-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
